### ISSUE TITLE
Dave Blogget - Head of Global Infrastructure and and Technical Operations KKR

### ISSUE THREAD

**Issue by aflies1** [promazo/ProMazo-Videos#4]
Video: https://drive.google.com/file/d/1bRdbkXd6WhP6dhUAJgC8KHcdiocl3yly/view?usp=sharing

Research:

**Comment by aflies1** [comment]
- [x] Research

- [x] Notes on Video

- [x] Video Pitch / Storyboard

- [ ] First Draft

- [ ] Edits

- [ ] Final Draft

**Comment by vbongard** [comment]
Hi Adam, I got through until the last 5 minutes of taking notes when I realized that this is not the KKR video that Brett wanted me to do next... I was nearly finished so I went ahead and did the pitch, but I'll pause work on this now and get working on the KKR Emilia video instead.

Here's the proposal for this video (the one with Dave): https://docs.google.com/document/d/1FWlTsD51Q2R9GPQgrIozKPBot3tVGBr3ex2EjdRmW3k/edit?usp=sharing

**Comment by vbongard** [comment]
Video 1, cut 1: https://drive.google.com/file/d/1EQtIrB_50gUUTx8BKQIHrxF4ai1X2WXD/view?usp=sharing

Video 2, cut 1: https://drive.google.com/file/d/1P0wdo7D702dFJRpMqkZma6qviyAfRYET/view?usp=sharing

**Comment by jaahmuhl** [comment]
@vbongard 

Video 1, cut 1: 
Q1: Can you describe what it was like to go straight from high school to the working world? 
Q2: What are the benefits of getting a formal degree?

Video 2, cut 1:
Q1: What role did mentors and coaches play in helping you succeed in your career?
Q3: How can a young professional stand out to their manager? And cut out from 4:11-4:45.

**Comment by vbongard** [comment]
@jaahmuhl 

Hi Brett,

Below are the updated cuts! Also, I got your email with the transcript from Rev, but I don't see your notes on it. Is there something I'm missing? I'm happy to do a third video, I just couldn't see the notes on what you want to include in it.

Video 1, cut 2: https://drive.google.com/file/d/1_SgDPvt1cHaO8iuF85tfM4jpvszu1gbx/view?usp=sharing

Video 2, cut 2: https://drive.google.com/file/d/1FYfFtkLRHn_9F-gQy05TYGNAbD75hxJt/view?usp=sharing

**Comment by jaahmuhl** [comment]
Video 1, cut 2: Question 1: Why did you go to get your degree later in life?

Video 2, cut 2: on minute 4:11-4:13 it goes to black screen for two seconds.

Video 3: Ok so Rev is a little touchy in regards to the way the notes display. I made a highlight of the two and then on the word before I put in a comment. Do you want to do a quick meeting to go through how I'm doing it?

thanks.
Brett

@vbongard 
@mikepromazo

**Comment by vbongard** [comment]
Hi Brett,

I checked again and I found the notes and highlighted questions! I put together a third video and made the edits to the first two. Here are the cuts:

Vide 1, cut 3: https://drive.google.com/file/d/1i6cmGWgefniIInIwWLNdNqSzkjnGs8nM/view?usp=sharing

Video 2, cut 3: https://drive.google.com/file/d/1rhGp-XoN_yv6xdrJYLpnxdej-E816kOm/view?usp=sharing

Video 3, cut 1: https://drive.google.com/file/d/1-tTvyU2IXJ5Qy8YH32pQb2jwRaWbGcYb/view?usp=sharing

@jaahmuhl 
@mikepromazo

**Comment by jaahmuhl** [comment]
@vbongard 

The videos look great. Only thing is the third video is an hour long but only 3:23 in actual content length.

**Comment by vbongard** [comment]
@jaahmuhl Oh,  weird! I fixed it and re-uploaded: https://drive.google.com/file/d/1VoyvkARfDfsU_RAv70V1hl_9re70TrEJ/view?usp=sharing

@mikepromazo

**Comment by jaahmuhl** [comment]
Blurb for: https://drive.google.com/file/d/1i6cmGWgefniIInIwWLNdNqSzkjnGs8nM/view

Can you still get a job without a college degree? 

(Dave Blogget) the Global Head of Infrastructure and Technical Operations at (KKR) breaks down why he is open to these types of candidates and what he thinks you get from a more formal education.

Interviewers: (Brett Hummel) & (Baptiste Bouvier)

Editor: (Victoria Bongard)

#promazo, #promazoexecinterviews, #kkr, #collegedegree
